.section .rodata

#include "data_macros.S"

overlay mrt_001
overlay mrt_002
overlay mrt_003
overlay mrt_004
overlay mrt_005
overlay mrt_006
overlay mrt_007
overlay mrt_008
overlay mrt_009
overlay mrt_010

datafile tex1_pal, data/tex1.pal
datafile tex1_tex, data/tex1.tex
datafile tex2_pal, data/tex2.pal
datafile tex2_tex, data/tex2.tex

datafile intro1_pal, data/intro1.pal
datafile intro1_tex, data/intro1.tex
datafile intro2_pal, data/intro2.pal
datafile intro2_tex, data/intro2.tex
datafile intro3_pal, data/intro3.pal
datafile intro3_tex, data/intro3.tex
datafile intro4_pal, data/intro4.pal
datafile intro4_tex, data/intro4.tex
datafile intro5_pal, data/intro5.pal
datafile intro5_tex, data/intro5.tex
datafile intro6_pal, data/intro6.pal
datafile intro6_tex, data/intro6.tex
datafile intro7_pal, data/intro7.pal
datafile intro7_tex, data/intro7.tex
datafile intro8_pal, data/intro8.pal
datafile intro8_tex, data/intro8.tex
datafile intro9_pal, data/intro9.pal
datafile intro9_tex, data/intro9.tex
datafile credits_pal, data/credits.pal
datafile credits_tex, data/credits.tex

datafile sample_bank_bin   data/sample_bank.bin
datafile microunits_mod_bin data/microunits.mod.bin

datafile offsets,    data/sphere/offsets.raw
datafile sphere_tex, data/sphere/sphere.tex
datafile sphere_pal, data/sphere/sphere.pal
